train:
  # Storage
  data: ./data

  # Task
  num_labels: 35

  # Training
  num_workers: 16

  # Optimizer
  lr_min: 0.000001
  lr_max_epochs: 400
  lr_scheduler: step_lr
  lr_warmup_epochs: 0
  weight_decay: 0.1

  # Feature extraction
  featurizer: log-mfsc
  n_mels: 64

  # Model
  prc_latent_dim: 128
  latent_weight_norm: kaiming

  prc_input_channels: 192
  prc_input_axis: 1
  prc_num_freq_bands: 64
  prc_max_freq: 224.0
  prc_depth: 6
  prc_cross_heads: 1
  prc_latent_heads: 8
  prc_cross_dim_head: 64
  prc_latent_dim_head: 64
  prc_attn_dropout: 0.0
  prc_ff_dropout: 0.0
  prc_weight_tie_layers: 1
  prc_fourier_encode_data: 1
  prc_self_per_cross_attn: 1
  prc_freeze_latents: 0

# Augmentations
  time_shift_p: 0.6
  resample_p: 1.0
  background_noise_p: 1.0
  specaugment_p: 1.0